apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tetragon
  namespace: kube-system
spec:
  interval: 1h
  releaseName: tetragon

  chart:
    spec:
      chart: tetragon
      version: ">=1.6.0 <2.0.0"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
