apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tetragon
  namespace: kube-system
spec:
chart:
  spec:
    chart: tetragon
    version: "1.1.0"
    sourceRef:
      kind: HelmRepository
      name: cilium
      namespace: flux-system
  interval: 5m
  values:
    global:
      ebpf: true
