apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tetragon
  namespace: kube-system
spec:
  chart:
    spec:
      chart: tetragon
      version: "1.15.0" # adjust version if needed
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  interval: 5m
  values:
    global:
      ebpf: true
