apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: monitor-shadow-access
spec:
  kprobes:
  - call: "sys_openat"
    syscall: true
    args:
    - index: 1
      type: "string"
    selectors:
    - matchArgs:
      - index: 1
        operator: "Equal"
        values:
        - "/etc/shadow"
