apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
  namespace: kube-system
spec:
  interval: 5m
  releaseName: falco
  chart:
    spec:
      chart: falco
      version: "7.0.2"
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: flux-system

  values:
    # 1️⃣ Force modern eBPF (NO kernel modules)
    driver:
      kind: modern-bpf

    # 2️⃣ Disable falcoctl completely (fixes read-only FS)
    falcoctl:
      enabled: false

    # 3️⃣ Disable plugins the CORRECT way (no Helm breakage)
    falco:
      load_plugins: false
      engine: modern_ebpf
      privileged: true
      json_output: true
      log_stderr: true
      log_level: info

    # 4️⃣ Pin modern Falco image (2026 compatible)
    image:
      repository: falcosecurity/falco
      tag: 0.38.0
      pullPolicy: IfNotPresent

    # 5️⃣ Custom detection rule
    customRules:
      rules-custom.yaml: |
        - rule: Shell inside container
          desc: Detect shell execution in a container
          condition: container and proc.name in (bash, sh, zsh)
          output: "Shell spawned in container (user=%user.name container=%container.name)"
          priority: WARNING
