apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
  namespace: kube-system
spec:
  interval: 5m
  releaseName: falco
  chart:
    spec:
      chart: falco
      version: ">=7.0.2"       # Pin to modern 2026-compatible chart
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: flux-system
  values:
    # 1. Use the Modern BPF engine (bundled in the 0.38.0+ binary)
    driver:
      kind: modern-bpf

    # 2. Disable the falcoctl sidecar to fix "read-only filesystem" errors
    falcoctl:
      artifact:
        install:
          enabled: false
        follow:
          enabled: false

    # 3. Disable external plugins to prevent API version mismatch
    services:
      plugins: []
    load_plugins: []

    # 4. Use the modern Falco image
    image:
      repository: falcosecurity/falco
      tag: 0.38.0
      pullPolicy: IfNotPresent

    # 5. Runtime configuration for WSL2 / container environments
    falco:
      privileged: true
      engine: modern_ebpf
      json_output: true
      log_stderr: true
      log_level: info

    # 6. Custom security rule
    customRules:
      rules-custom.yaml: |
        - rule: Shell inside container
          desc: Detect shell execution in a container
          condition: container and proc.name in (bash, sh, zsh)
          output: "Shell spawned in container (user=%user.name container=%container.name)"
          priority: WARNING
