apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: falco
      version: ">=1.14.0"
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: flux-system
  values:
    # 1. Force the modern engine bundled in the binary (CO-RE)
    driver:
      kind: modern-bpf
    
    # 2. Upgrade the Falco binary to 2026 standard (v0.38+)
    image:
      repository: falcosecurity/falco
      tag: 0.38.0
    
    # 3. Enable required security contexts for BPF injection
    falco:
      privileged: true

    # 4. Your existing custom rules
    customRules:
      rules-custom.yaml: |
        - rule: Shell inside container
          desc: Detect shell execution in a container
          condition: container and proc.name in (bash, sh, zsh)
          output: Shell spawned in container (user=%user.name container=%container.name)
          priority: WARNING
