apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: falco
      version: "1.14.0"
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: flux-system
  values:
    driver:
      kind: modern-bpf
    
    # IMPORTANT: Clear out legacy extraArgs if they exist in your yaml
    extraArgs: [] 

    # In modern versions, K8s sync is handled via the config file, not flags
    tty: true
    
    customRules:
      rules-custom.yaml: |
        - rule: Shell inside container
          desc: Detect shell execution in a container
          condition: container and proc.name in (bash, sh, zsh)
          output: Shell spawned in container (user=%user.name container=%container.name)
          priority: WARNING
