apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monitoring
  namespace: monitoring
spec:
  interval: 1h
  releaseName: monitoring

  chart:
    spec:
      chart: kube-prometheus-stack
      version: ">=60.0.0 <90.0.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system

  install:
    createNamespace: true

  upgrade:
    cleanupOnFail: true
