apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monitoring
  namespace: monitoring
spec:
chart:
  spec:
    chart: kube-prometheus-stack
    version: "60.0.0"
    sourceRef:
      kind: HelmRepository
      name: prometheus-community
      namespace: flux-system
  interval: 5m

